create table if not exists public.food_consumption (
  id bigint generated by default as identity primary key,
  date date not null,
  day_of_week text not null,
  is_holiday boolean default false,
  expected_people integer not null check (expected_people >= 0),
  food_prepared integer not null check (food_prepared >= 0),
  food_consumed integer not null check (food_consumed >= 0),
  food_wasted integer generated always as (greatest(food_prepared - food_consumed, 0)) stored,
  created_at timestamptz default now()
);

create table if not exists public.demand_predictions (
  id bigint generated by default as identity primary key,
  prediction_date date not null,
  expected_people integer not null,
  is_holiday boolean default false,
  predicted_demand integer not null,
  recommended_preparation integer not null,
  confidence numeric(5,2),
  created_at timestamptz default now()
);

create table if not exists public.redistribution_partners (
  id bigint generated by default as identity primary key,
  name text not null,
  organization_type text,
  location text,
  contact text,
  capacity integer default 0,
  available boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.surplus_food (
  id bigint generated by default as identity primary key,
  food_name text not null,
  quantity integer not null check (quantity > 0),
  pickup_location text not null,
  expiry_time timestamptz,
  status text default 'available',
  partner_id bigint references public.redistribution_partners(id),
  created_at timestamptz default now()
);

create index if not exists idx_food_consumption_date
  on public.food_consumption(date);

create index if not exists idx_predictions_date
  on public.demand_predictions(prediction_date);

create index if not exists idx_surplus_status
  on public.surplus_food(status);
