create table if not exists public.surplus_food (
  id bigint generated by default as identity primary key,
  food_name text not null,
  quantity integer not null check (quantity > 0),
  unit text not null default 'meals',
  available_date date not null default current_date,
  expiry_time timestamptz,
  source_name text not null,
  source_type text not null default 'restaurant',
  organization_name text,
  organization_type text,
  pickup_status text not null default 'available'
    check (pickup_status in ('available', 'reserved', 'picked_up', 'expired')),
  distance_km numeric(6,2),
  created_at timestamptz default now()
);


alter table public.surplus_food
  add column if not exists pickup_status text not null default 'available';

alter table public.surplus_food
  add column if not exists organization_name text;

alter table public.surplus_food
  add column if not exists organization_type text;

alter table public.surplus_food
  add column if not exists distance_km numeric(6,2);


alter table public.surplus_food
  add column if not exists available_date date default current_date;

alter table public.surplus_food
  add column if not exists source_name text;

alter table public.surplus_food
  add column if not exists source_type text default 'restaurant';

alter table public.surplus_food
  add column if not exists unit text default 'meals';

alter table public.surplus_food
  add column if not exists expiry_time timestamptz;

create index if not exists surplus_food_status_idx
on public.surplus_food(pickup_status);

create index if not exists surplus_food_date_idx
on public.surplus_food(available_date);
